using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    [Authorize]
    [ApiController]
    [Route("[controller]")]
    public class EmployeeController : ControllerBase
    {
        [HttpGet]
        public List<Employee> Get()
        {
            List<Employee> empList = new List<Employee>();
            var EmployeeName = new List<string>() { "NATHANIEL FORD","GARY JIMENEZ","ALBERT PARDINI","CHRISTOPHER CHONG","PATRICK GARDNER","DAVID SULLIVAN","ALSON LEE","DAVID KUSHNER","MICHAEL MORRIS","JOANNE HAYES-WHITE","ARTHUR KENNEY","PATRICIA JACKSON","EDWARD HARRINGTON","JOHN MARTIN","DAVID FRANKLIN","RICHARD CORRIEA","AMY HART","SEBASTIAN WONG","MARTY ROSS","ELLEN MOFFATT","VENUS AZAR","JUDY MELINEK","GEORGE GARCIA","VICTOR WYRSCH","JOSEPH DRISCOLL","GREGORY SUHR","JOHN HANLEY","AYMOND GUZMAN","DENISE SCHMITT","MONICA FIELDS","HARLAN KELLY-JR"};
            var JobTitle = new List<string>() { "GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY","CAPTAIN III (POLICE DEPARTMENT)","CAPTAIN III (POLICE DEPARTMENT)","WIRE ROPE CABLE MAINTENANCE MECHANIC","DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)","ASSISTANT DEPUTY CHIEF II","BATTALION CHIEF, (FIRE DEPARTMENT)","DEPUTY DIRECTOR OF INVESTMENTS","BATTALION CHIEF, (FIRE DEPARTMENT)","CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)","ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)","CAPTAIN III (POLICE DEPARTMENT)","EXECUTIVE CONTRACT EMPLOYEE","DEPARTMENT HEAD V","BATTALION CHIEF, (FIRE DEPARTMENT)","COMMANDER III, (POLICE DEPARTMENT)","DEPARTMENT HEAD V","CAPTAIN, EMERGENCYCY MEDICAL SERVICES","BATTALION CHIEF, (FIRE DEPARTMENT)","ASSISTANT MEDICAL EXAMINER","ASSISTANT MEDICAL EXAMINER","ASSISTANT MEDICAL EXAMINER","CAPTAIN, FIRE SUPPRESSION","BATTALION CHIEF, (FIRE DEPARTMENT)","CAPTAIN, FIRE SUPPRESSION","CHIEF OF POLICE","CAPTAIN, FIRE SUPPRESSION","BATTALION CHIEF, (FIRE DEPARTMENT)","DEPUTY CHIEF III (POLICE DEPARTMENT)","DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)","EXECUTIVE CONTRACT EMPLOYEE"};
            var TotalPay = new List<String>() { "567595.43","538909.28","335279.91","332343.61","326373.19","316285.74","315981.05","307899.46","303427.55","302377.73","299494.17","297608.92","294580.02","292671.62","286347.05","286213.86","284720.43","278569.21","276434.22","274550.25","274190.27","273771.21","273702.71","270672.63","270324.91","267992.59","265784.56","265463.46","264074.6","261366.14","260297.66"};

            for (int i = 0; i < 30; i++)
            {
                empList.Add(new Employee()
                {
                    EmployeeID = i + 1,
                    Name = EmployeeName[i],
                    Role = JobTitle[i],
                    Salary = TotalPay[i]
                });
            }

            return empList;
        }

        [HttpGet("{id:int}")]
        public List<Employee> Get(int id)
        {
            List<Employee> empList = new List<Employee>();
            if (id < 31 && id > 0)
            {
                
                var EmployeeName = new List<string>() { "NATHANIEL FORD", "GARY JIMENEZ", "ALBERT PARDINI", "CHRISTOPHER CHONG", "PATRICK GARDNER", "DAVID SULLIVAN", "ALSON LEE", "DAVID KUSHNER", "MICHAEL MORRIS", "JOANNE HAYES-WHITE", "ARTHUR KENNEY", "PATRICIA JACKSON", "EDWARD HARRINGTON", "JOHN MARTIN", "DAVID FRANKLIN", "RICHARD CORRIEA", "AMY HART", "SEBASTIAN WONG", "MARTY ROSS", "ELLEN MOFFATT", "VENUS AZAR", "JUDY MELINEK", "GEORGE GARCIA", "VICTOR WYRSCH", "JOSEPH DRISCOLL", "GREGORY SUHR", "JOHN HANLEY", "AYMOND GUZMAN", "DENISE SCHMITT", "MONICA FIELDS", "HARLAN KELLY-JR" };
                var JobTitle = new List<string>() { "GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY", "CAPTAIN III (POLICE DEPARTMENT)", "CAPTAIN III (POLICE DEPARTMENT)", "WIRE ROPE CABLE MAINTENANCE MECHANIC", "DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)", "ASSISTANT DEPUTY CHIEF II", "BATTALION CHIEF, (FIRE DEPARTMENT)", "DEPUTY DIRECTOR OF INVESTMENTS", "BATTALION CHIEF, (FIRE DEPARTMENT)", "CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)", "ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)", "CAPTAIN III (POLICE DEPARTMENT)", "EXECUTIVE CONTRACT EMPLOYEE", "DEPARTMENT HEAD V", "BATTALION CHIEF, (FIRE DEPARTMENT)", "COMMANDER III, (POLICE DEPARTMENT)", "DEPARTMENT HEAD V", "CAPTAIN, EMERGENCYCY MEDICAL SERVICES", "BATTALION CHIEF, (FIRE DEPARTMENT)", "ASSISTANT MEDICAL EXAMINER", "ASSISTANT MEDICAL EXAMINER", "ASSISTANT MEDICAL EXAMINER", "CAPTAIN, FIRE SUPPRESSION", "BATTALION CHIEF, (FIRE DEPARTMENT)", "CAPTAIN, FIRE SUPPRESSION", "CHIEF OF POLICE", "CAPTAIN, FIRE SUPPRESSION", "BATTALION CHIEF, (FIRE DEPARTMENT)", "DEPUTY CHIEF III (POLICE DEPARTMENT)", "DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)", "EXECUTIVE CONTRACT EMPLOYEE" };
                var TotalPay = new List<String>() { "567595.43", "538909.28", "335279.91", "332343.61", "326373.19", "316285.74", "315981.05", "307899.46", "303427.55", "302377.73", "299494.17", "297608.92", "294580.02", "292671.62", "286347.05", "286213.86", "284720.43", "278569.21", "276434.22", "274550.25", "274190.27", "273771.21", "273702.71", "270672.63", "270324.91", "267992.59", "265784.56", "265463.46", "264074.6", "261366.14", "260297.66" };

                empList.Add(new Employee()
                {
                    EmployeeID = id,
                    Name = EmployeeName[id - 1],
                    Role = JobTitle[id - 1],
                    Salary = TotalPay[id - 1]
                });
            }
            return empList;
        }
    }
}
